### ISSUE TITLE
GlobalStorageUpdateRequiredException: Storage server '123'

### ISSUE THREAD

**Issue by luiscla27** [hmvictor/nb-sonarlint#7]
Hello, the following exception is being thrown immediately after NB starts:

```
org.sonarsource.sonarlint.core.client.api.exceptions.GlobalStorageUpdateRequiredException: Storage of server '123' requires an update
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.checkUpdateStatus(ConnectedSonarLintEngineImpl.java:220)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:342)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:334)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.checkIfGlobalStorageNeedUpdate(ConnectedSonarLintEngineImpl.java:195)
	at org.radar.radarlint.SonarLintScanner.get(SonarLintScanner.java:125)
	at org.radar.radarlint.SonarLintScanner.get(SonarLintScanner.java:48)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
Caused: java.util.concurrent.CompletionException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[catch] at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

This is my NB environment:
- Product Version: **Apache NetBeans IDE 12.1**
- Updates: **NetBeans IDE is updated to version NetBeans 8.2 Patch 2**
- Java: **12.0.2; OpenJDK 64-Bit Server VM 12.0.2+10**
- Runtime: **OpenJDK Runtime Environment 12.0.2+10**
- System: **Windows 10 version 10.0 running on amd64; Cp1252; es_MX (nb)**

![image](https://user-images.githubusercontent.com/29953012/97235614-d5921f80-17a8-11eb-8fc8-94f8bb36d26a.png)
![image](https://user-images.githubusercontent.com/29953012/97235662-f78ba200-17a8-11eb-946b-9c47e3b13d6f.png)
![image](https://user-images.githubusercontent.com/29953012/97235681-01150a00-17a9-11eb-80a1-f5f7ae22e739.png)

**Comment by oyarzun** [comment]
@luiscla27 #1 should fix this issue. @hmvictor, all of @awatry PRs are quite useful any chance they can be merged to master?
